server:
  port: 8080

spring:
  profiles:
    # w dev możesz odpalić: SPRING_PROFILES_ACTIVE=dev
    # w prod: SPRING_PROFILES_ACTIVE=prod
    active: dev
  datasource:
    url: jdbc:h2:mem:jmlwmb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none   # <-- kluczowe: nie waliduj zanim Flyway zrobi schema
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
app:
  cors:
    allowed-origins: "http://localhost:4200"
  security:
    cookie:
      # prod: true (cookie tylko po HTTPS)
      secure: ${APP_COOKIE_SECURE:false}
      # jeśli frontend/backend na różnych originach w prod, rozważ: None (wtedy secure musi być true)
      same-site: ${APP_COOKIE_SAMESITE:Lax}
    jwt:
      issuer: "spring-angular-security"
      access-ttl-minutes: 10
      refresh-ttl-days: 14
      secret: K9vA1c7RZPqE9W4dYxF8sL2nM6H0JQeB
      # secret: ${APP_JWT_SECRET:}